### ISSUE TITLE
How to installation, usage instructions?

### ISSUE THREAD

**Issue by aasutossh** [atelierbram/Base2Tone-nvim#1]

**Comment by atelierbram** [comment]
@aasutossh I will update the readme very soon. 
But you install these colorschemes just like you would any other plugin. 

Activate in one of your lua config files like:

```lua
vim.cmd("colorscheme base2tone_evening_dark")
```

or in command mode: `colo base2tone_evening_dark` or any of the other variations &hellip;

**Comment by aasutossh** [comment]
i was able to install it.
do we plan to support neeovim features such as treesitter?

**Comment by atelierbram** [comment]
It already supports Treesitter, it is written in Lua and specially adapted with Treesitter. It supports quite a few of the popular plugins like Telescope, Nvim-Tree, IndentBlankline, GitSigns.

**Comment by aasutossh** [comment]
That's so good to hear.

**Comment by aasutossh** [comment]
I really like https://github.com/rakr/vim-two-firewatch theme. And wanted some latest neovim features and plugins support with it.
Do you have a guide to port themes to add supports for such?

**Comment by atelierbram** [comment]
No easy porting AFAIK, but what I use is this [colorgen-nvim](https://github.com/ChristianChiarulli/colorgen-nvim) colorscheme generator tool for NeoVim. It is written in Rust, so one has to install that programming language as well. Good luck!

**Comment by aasutossh** [comment]
> No easy porting AFAIK, but what I use is this [colorgen-nvim](https://github.com/ChristianChiarulli/colorgen-nvim) colorscheme generator tool for NeoVim. It is written in Rust, so one has to install that programming language as well. Good luck!

Thank you for the tip.
Edit: could you provide one sample file for colorgen-nvim for duotone themes?
