### ISSUE TITLE
Very dim selection colors for some themes, hard to notice

### ISSUE THREAD

**Issue by aasutossh** [atelierbram/Base2Tone-nvim#3]
examples:

evening dark
<img width="234" alt="image" src="https://user-images.githubusercontent.com/18498932/201251313-715a1eb5-5495-4ab6-9f95-2bdf20fb8070.png">
drawbridge dark
<img width="293" alt="image" src="https://user-images.githubusercontent.com/18498932/201251460-98837cf6-6c82-48b3-8c7b-ed2a6e09c5ca.png">

**Comment by aasutossh** [comment]
forest light
<img width="229" alt="image" src="https://user-images.githubusercontent.com/18498932/201252831-384e8017-c7ac-4b31-bc55-f47ea80590a2.png">

edit:
but selection color is okay for this
<img width="446" alt="image" src="https://user-images.githubusercontent.com/18498932/201252987-1b0df048-d082-4486-a772-2bf2cf043729.png">

**Comment by atelierbram** [comment]
@aasutossh thanks for the heads up, definitely an oversight. I increased the contrast for the "Visual" highlight background with the page background color _in the dark themes_ with one instance.  For _the light themes_ I thought it better to differentiate between the highlight from the *current line* background color, so there is a different color for the "Visual" highlight (in relation to the page background color) there now. Please see if these latest updates work for you &hellip;.

**Comment by aasutossh** [comment]
Thank you for the update. I'll report back after I fetch the updates.

**Comment by aasutossh** [comment]
the multilined html formatted codes are fine but now, I see a different issue.
it's fine in multilined
<img width="254" alt="image" src="https://user-images.githubusercontent.com/18498932/203060670-b3d463ef-5f2a-48d0-be6f-805db0aba1b8.png">


but selection not visible for single line
<img width="574" alt="image" src="https://user-images.githubusercontent.com/18498932/203060803-676c417a-9e25-45b1-b6e7-78149d9d4fa1.png">

**Comment by atelierbram** [comment]
@aasutossh Can you explain this issue a bit further, either I can't reproduce this, or don't know what you mean. We are talking about a selection in **visual mode** no?

**Comment by aasutossh** [comment]
yes. let me make a short screenrecord. and post it. EDIT: The theme is evening dark btw.

https://user-images.githubusercontent.com/18498932/203219021-eee226a2-6bcb-42b7-95bb-63213b03718c.mov

when i select text using `v` in a single line tag, the background color and selected color are same.
EDIT:
Notice it at 00:05 for single line and 00:18 for multi line tag.

EDIT:
<img width="510" alt="image" src="https://user-images.githubusercontent.com/18498932/203219746-114c039a-5c41-4e26-96af-08d27d94915a.png">
but for cave light it's looking good.

**Comment by atelierbram** [comment]
@aasutossh This is odd, I can't wrap my brain around this because I don't have this issue on my Neovim setup (also not in the dark themes) and can't - or don't know how to - reproduce it. For you to have this issue only in the dark themes makes it even more strange to me. I am thinking maybe some declaration in the Treesitter part of the dark themes, but I don't know for nothing obviously different (from the light themes) sticks out to me.
So I need your help to troubleshoot this issue further. The example you gave seems to be some kind of Vue file, but do you have the same problem in a PHP or plain HTML file? This to exclude the possibility this issue being a combination of one or more of your plugins (like maybe some language-server) and the dark themes. I know this seems to be neither here nor there or even farfetched but that's where debugging should start it seems to me for now.

**Comment by aasutossh** [comment]
If I find anything about this then I'll report back.

**Comment by aasutossh** [comment]
<img width="327" alt="image" src="https://user-images.githubusercontent.com/18498932/203810735-391e389a-c50d-4e35-a6da-8fd2373d45be.png">
Seems like it exists for the plain html file too. Barely noticeable.

EDIT: I am using [LunarVim](https://lunarvim.org). Might be some of the plugins interfering.

**Comment by atelierbram** [comment]
Have you tried to run `:TSUpdate` or `:checkhealth`?

**Comment by aasutossh** [comment]
No I haven't. I'll do that later.

**Comment by aasutossh** [comment]
> Have you tried to run `:TSUpdate` or `:checkhealth`?

Nothing to report. All normal.

**Comment by atelierbram** [comment]
Something to try maybe is to toggle plugins temporarily off in the `config.lua` file of your setup, then restart Neovim to see if the problem persists &hellip;

**Comment by aasutossh** [comment]
https://github.com/andymass/vim-matchup was causing the issue.
```
lvim.builtin.treesitter.matchup.enable = true
```
I had forgotten to add the above line in my config.

**Comment by atelierbram** [comment]
Good to know you found the root cause of this issue, &hellip; take care!
