### ISSUE TITLE
indent_blankline's context indent highlight not working in this theme

### ISSUE THREAD

**Issue by towry** [atelierbram/Base2Tone-nvim#4]
See the feature: https://github.com/lukas-reineke/indent-blankline.nvim#with-context-indent-highlighted-by-treesitter

Working in gruvbox:

![截屏2022-12-06 19 16 23](https://user-images.githubusercontent.com/8279858/205897562-20af7a3f-371f-4250-8ccd-e1787cdff2a5.png)

**Comment by atelierbram** [comment]
@towry I gave the context char a bit more contrast, please see if this works for you after updating.

**Comment by towry** [comment]
<img width="470" alt="截屏2022-12-08 01 07 16" src="https://user-images.githubusercontent.com/8279858/206244491-fbd3fccb-c4c5-4362-b55f-33f2a85a15a2.png">


Seems working, thanks.
